version: '3.5'

services:
  gradle: &gradle
    image: gradle:5.2.1-alpine
    working_dir: /app
    entrypoint: gradle
    volumes:
      - .:/app

  build: &build
    <<: *gradle
    command: -t build