version: '3.5'

services:
  # Java core container for excel and word file processing
  gradle: &gradle
    image: gradle:5.2.1-alpine
    working_dir: /app
    entrypoint: gradle
    volumes:
      - .:/app

  gradlew: &gradlew
    <<: *gradle
    entrypoint: ./gradlew

  build: &build
    <<: *gradle
    command: -t build